<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>healthcare-tests - TS_RegressionTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1286ccc6-2057-418d-87af-23d00cc6cd0e</testSuiteGuid>
   <testCaseLink>
      <guid>b3c08dcd-1b95-447d-88d1-bc076ff2b09c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/First Test Case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>12b1ed24-3d2b-4bed-87e1-7c72470cdce7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>true</defaultValue>
         <description></description>
         <id>ed37fdce-0449-464a-931c-00d982c14c17</id>
         <masked>false</masked>
         <name>individualRun</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Main Test Cases/TC1_Verify Successful Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14d98e7b-4ac8-4e28-8ce7-394001d188f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a97344e7-5f9c-4936-92a2-d85e5463f3c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>ed37fdce-0449-464a-931c-00d982c14c17</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4bf2157-13c0-4c5f-875c-fa60a7e7a2fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>true</defaultValue>
         <description></description>
         <id>a4a2dc76-b32e-417e-9d30-78f43f736838</id>
         <masked>false</masked>
         <name>individualRun</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Main Test Cases/TC2_Verify Successful Appointment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>a4a2dc76-b32e-417e-9d30-78f43f736838</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>955abe25-4029-43e2-b02f-57315c1ade49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC3_Visual Testing Example</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
